DROP TABLE IF EXISTS TBL_PERSONS;

CREATE TABLE TBL_PERSONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  identification int(15) NOT NULL,
  name VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) DEFAULT NULL,
  dateofbirth DATE NOT NULL
);